version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodbdata:/data/db
  api:
    build: ../backend
    environment:
      - MONGO_HOST_NAME=mongo
      - MONGO_PORT=27017
      - MONGO_COLLECTION_NAME=schemes
      - MONGO_DATABASE_NAME=gestalt
    ports:
    - "5000:5000"
    - "5001:5001"
    depends_on:
    - mongo
  frontend:
    build: ../frontend
    ports:
    - "80:80"
    depends_on:
    - api
volumes:
  mongodbdata:
    driver: local